### ISSUE TITLE
addTrack

### ISSUE THREAD

**Issue by thecodeduchess** [f-shade/jamming#2]
https://github.com/f-shade/jamming/blob/eb66dc8b673d6a5c4bb460043cda4649bcfb7519/src/Components/App/App.js#L32-L42

I really like your implementation of this method. I have literally seen 100 different implementations for this method. It is always interesting to see what people come up with to do the same thing.

**Comment by f-shade** [comment]
Excellent, thank you!  I appreciate the positive notes.
